package ui

import "github.com/charmbracelet/lipgloss"

var (
    ColorBlack     = lipgloss.Color("#000000")
    ColorDarkGray  = lipgloss.Color("#1a1a1a")
    ColorGray      = lipgloss.Color("#3a3a3a")
    ColorLightGray = lipgloss.Color("#888888")
    ColorWhite     = lipgloss.Color("#ffffff")
    ColorGreen     = lipgloss.Color("#00ff00")
    ColorRed       = lipgloss.Color("#ff0000")
    ColorPurple    = lipgloss.Color("#00aa00")
    ColorBlue      = lipgloss.Color("#00cc00")
    ColorYellow    = lipgloss.Color("#00ff00")
    ColorOrange    = lipgloss.Color("#00dd00")

    AppStyle = lipgloss.NewStyle().Background(ColorBlack).Foreground(ColorGreen)
    HeaderStyle = lipgloss.NewStyle().Background(ColorGreen).Foreground(ColorBlack).Bold(true).Padding(0, 1)
    NetworkNameStyle = lipgloss.NewStyle().Background(ColorGreen).Foreground(ColorBlack).Bold(true)
    UsernameStyle = lipgloss.NewStyle().Background(ColorGreen).Foreground(ColorBlack)
    StatusConnectedStyle = lipgloss.NewStyle().Background(ColorGreen).Foreground(ColorBlack).Bold(true)
    StatusDisconnectedStyle = lipgloss.NewStyle().Background(ColorGreen).Foreground(ColorGray).Bold(true)
    DividerStyle = lipgloss.NewStyle().Foreground(ColorGreen)
    MessageStyle = lipgloss.NewStyle().Foreground(ColorGreen)
    SystemMessageStyle = lipgloss.NewStyle().Foreground(ColorGreen)
    TaskMessageStyle = lipgloss.NewStyle().Foreground(ColorYellow)
    ErrorStyle = lipgloss.NewStyle().Foreground(ColorRed)
    SuccessStyle = lipgloss.NewStyle().Foreground(ColorGreen)
    InputStyle = lipgloss.NewStyle().Foreground(ColorGreen)
    HintStyle = lipgloss.NewStyle().Foreground(ColorLightGray)
    TimeStyle = lipgloss.NewStyle().Foreground(ColorLightGray)
    UsernameInMessageStyle = lipgloss.NewStyle().Foreground(ColorGreen).Bold(true)
    ScrollbarStyle = lipgloss.NewStyle().Foreground(ColorGreen)
)
